apiVersion: v1
kind: Service
metadata:
  name: {{ include "momentum.appName" . }}
  labels:
    {{- include "momentum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "momentum.selectorLabels" (dict "ctx" . "component" "app") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
